EMBEDLY_KEY: 'c356c4f7a49644a4b4c83789982388cf'
CLOUDMAILIN_FORWARD_ADDRESS:    '75b018d607fb26cc7d88@cloudmailin.net'
CLOUDMAILIN_PASSWORD:           '035ef848321b'
CLOUDMAILIN_SECRET:             '527a7878807dc5fd985b'
CLOUDMAILIN_USERNAME:           'app21831629@heroku.com'
